# Generated by Django 3.0.4 on 2020-03-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useit_api', '0003_auto_20200307_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='fix_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fix_id',
        ),
    ]
