# Generated by Django 3.0.4 on 2020-03-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useit_api', '0005_auto_20200307_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='fix_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='fix_id',
            field=models.IntegerField(),
        ),
    ]
