# Generated by Django 3.0.4 on 2020-03-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useit_api', '0006_auto_20200307_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
