# Generated by Django 3.0.4 on 2020-03-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useit_register', '0002_auto_20200307_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('fix_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='fix_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
