# Generated by Django 3.0.4 on 2020-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useit_register', '0004_auto_20200307_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='fix_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='fix_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
